#!/usr/bin/env dash

if [ "$MVE_CONFIGS/$CONFIG/history/"* = "$MVE_CONFIGS/$CONFIG/history/*" ]
then
    echo 'there were no treated files'
    exit 50
fi

count=0
for treated in $MVE_CONFIGS/$CONFIG/history/*
do
    if [ $count -gt 1 ]
    then
        echo 'there was more than one treated file'
        exit 60
    fi

    # the good file should have still been edited
    if ! grep -F -q good "$treated"
    then
        echo 'the good file was not recorded to have been treated'
        echo 70
    fi

    count=$((count + 1))
done

if 

true
