#!/usr/bin/env dash

# errors should only be local to files that had errors
# others should be fine

err="$(mktemp)"
out="$(mktemp)"

trap 'rm -f "$err" "$out"' EXIT

. ../setup-env

./tamper-file || exit $?

./detect-problematic-files "$err" "$out" || exit $?

# the good file should have still been edited
# if grep -F -q good 

echo ''
echo 'treater successfully detected bad timestamps'
true
