#!/usr/bin/env dash

# errors should only be local to files that had errors
# others should be fine

err="$(mktemp)"
out="$(mktemp)"

trap 'rm -f "$err" "$out"' EXIT

. ../setup-env

log_step() {
    num=$1
    message="$2"

    echo ''
    printf '['
    clr 'bright_green' $num
    echo "] $message"
    echo ''

}

./tamper-file || exit $?
log_step 1 'tampered file'

# ./detect-problematic-files "$err" "$out" || exit $?
# log_step 2 'ran treater on problematic file'

# ./check-good-file || exit $?
# log_step 3 'checked that the good file still got treated properly'

# # TODO: add test number

# echo ''
# echo 'treater successfully detected bad timestamps'
# true
