#!/usr/bin/env dash

# run all tests given as command line argument where each is a file structured:
# ./[test]/run

run_and_maybe_show_output() {
    # run a test after already having changed into its folder
    # we change folders outside the function in case any errors are encountered

    status=0

    if [ $SHOW_OUTPUT = yes ]
    then
        {
            run
            status=$?
        } | sed -E 's/^/    /'
    else
        run > /dev/null 2>&1
        status=$?
    fi

    return $status
}

# allow scripts for each test to be run without ./ needed
export PATH=".:$PATH"

i=1
for raw in "$@"
do
    dir="$(dirname "$raw")"
    verify-name-in-terms "$NAME_TERMS" "$dir" || continue

    printf 'test [ %s of %d ]\n' $(clr bright_yellow $i) $TOTAL_TESTS

    cd "$dir"
    if run_and_maybe_show_output "$dir"
    then
        echo ''
        clr cyan 'passed'
        echo " tests in: $dir"
        echo ''
    else
        echo ''
        clr magenta 'failed'
        echo " tests in: $dir"
        echo ''
        exit 1
    fi
    cd ..

    i=$((i + 1))
done
