#!/usr/bin/env dash

export CONFIG=no-flags

python3 -m mve log make $CONFIG \
    --source='../videos' --renames="$(pwd)" --edits=outputs > /dev/null \
    || exit 10

# these have to be loaded from defaults

load_from_default () {
    name=$1
    # only booleans or numbers [yn]
    is_boolean=$2

    raw="$(grep -F $name mve/src/constants/defaults.py \
    | sed -E 's/ = /=/g' \
    | cut -d '=' -f2)"

    if [ $is_boolean = y ]
    then
        # Python booleans begin with capital letter, whereas JSON is snake_case
        printf '%s' "$raw" | tr 'A-Z' 'a-z'
    else
        printf '%s' "$raw"
    fi
}

grep -F -q "\"RECENT\": $(load_from_default RECENT y)" $MVE_CONFIGS/$CONFIG/config.json || exit 20
grep -F -q "\"NUM_PROCESSES\": $(load_from_default NUM_PROCESSES n)" $MVE_CONFIGS/$CONFIG/config.json || exit 30
# grep -F -q '"": 7' $MVE_CONFIGS/$CONFIG/config.json || exit 30
# grep -F -q '"USE_MOVIEPY": true' $MVE_CONFIGS/$CONFIG/config.json || exit 40
# grep -F -q '"MOVIEPY_THREADS": 5' $MVE_CONFIGS/$CONFIG/config.json || exit 50
# grep -F -q '"TESTING": true' $MVE_CONFIGS/$CONFIG/config.json || exit 60
# grep -F -q '"BOLD": true' $MVE_CONFIGS/$CONFIG/config.json || exit 70
