#!/usr/bin/env/dash

# check to see that problematic files may be re-edited

# original files were 01, 02, 03, 04 .mp4
# 01 -> bad
# 02 -> good
# 03 -> worse
# 04 -> [ not edited ]

# so the files should now be: 04, 01, 03
