#!/bin/dash

# set to a non-empty string value to turn on
VIEW=''

../setup-env

touch outputs/exists.mp4

cd src

[ -n "$VIEW" ] && sed -E -i '' '/^TESTING/s%True%False%' config.py

python3 viewer.py < ../cmds
