#!/usr/bin/env dash

# the sandbox is mainly for seeing what expected output should be  
# commands fed to the viewer are placed in the file `cmds`  
# since the sandbox testing constantly changes, this file should be ignored by git  

# set to a non-empty string value to turn on
VIEW=''

. setup-env
