#!/usr/bin/env dash

# usage: run [--clean]

# This is a wrapper script to ensure that tests are run in the virtual
# environment.
# Testing files are left for inspection by default.

# usage: run --

. .venv/bin/activate

# provide access to working directory shell scripts
PATH="$PATH:$(pwd)"

clean=no
for arg in "$@"
do
    case "$arg" in
        --clean) clean=yes ;;
    esac
done

find_tests() {
    # find any folder that has a run file and run a script on all such folders
    script="$1"
    find . -mindepth 2 -maxdepth 2 -name 'run' -exec "$script" {} +
}

export TOTAL_TESTS=$(find_tests count-tests)

find_tests test-all

nl
clr bright_green 'passed'
echo ' all tests!'

if [ $clean = yes ]
then
    clean-tests
fi

deactivate
