#!/usr/bin/env dash

[ -d .venv ] && rm -r .venv

python3 -m venv .venv            # create virtual environment .venv
.venv/bin/activate               # start the virtual environment
pip3 install -r requirements.txt # install dependencies
deactivate

./make-videos

echo 'sucessfully set up testing environment'
