#!/bin/dash

# the default config used for testing
export CONFIG=testing

[ -d configs ] && rm -r configs
mkdir configs

cd configs
mkdir $CONFIG
cd $CONFIG
for dir in errors history queue
do
    mkdir $dir
done
echo '[]' > remaining.json
cat << EOF > config.json
{
    "SOURCE": ["..", "..", "videos"],
    "RENAMES": [".."],
    "DESTINATION": ["..", "outputs"],

    "TESTING": true,
    "RECENT": false
}
EOF
cd ../..

cp -r ../../mve/src .
cd src
python3 generator.py $CONFIG > /dev/null
