#!/usr/bin/env dash

# if this is run from a stand-alone test, then helpers would not be in PATH
# only add this if it was not the case that the script was run from root

if ! [ "$RUN_FROM_ROOT" = yes ]
then
    export PATH="$(realpath ../helpers):$PATH"
    # deactivation occurs once the standalone test ends
    . ../.venv/bin/activate
fi

. mve-env

if [ ! -d ../../mve/mve ]
then
    echo "$(basename $0) failed because ../../mve/mve doesn't exist"
    echo "the mve project folder must exist in the parent of mve-tests"
    exit 15
fi
[ -d mve ] && rm -rf mve
cp -r ../../mve/mve .
# get rid of .git as well
rm -rf mve/.git

[ -d $MVE_CONFIGS ] && rm -r $MVE_CONFIGS
mkdir $MVE_CONFIGS

for dir in $EDITS $RENAMES
do
    [ -d $dir ] && rm -r $dir 
    mkdir $dir 
done

python3 -m mve log make \
    $CONFIG \
    --source '../videos' --renames $RENAMES --edits $EDITS \
    --testing \
    || exit 10

python3 -m mve log generator $CONFIG > /dev/null || exit 10

echo "set up test $(basename $(pwd))"
echo ''
