#!/bin/dash

for dir in 'errors' 'history' 'queue' 'outputs'
do
    [ -d "$dir" ] && rm -r "$dir"
    mkdir "$dir"
done

cp -r ../../mve/src .

cd src
echo '[]' > remaining.json

sed -E -i '' '/^SOURCE/s%\[.*\]%["../", "../", "videos"]%
/^RENAMES/s%\[.*\]%["../"]%
/^DESTINATION/s%\[.*\]%["../", "outputs"]%
/^TESTING/s%False%True%' config.py

python3 generator.py