#!/usr/bin/env dash

# run all tests given as command line argument where each is a file structured:
# ./[test]/run

i=1
alias nl='echo "" && echo ""'
for raw in "$@"
do
    printf 'test [ %s of %d ]\n' $(./clr bright_yellow $i) $TOTAL_TESTS

    dir="$(dirname "$raw")"
    cd "$dir"

    if run
    then
        nl
        ../clr cyan 'passed'
        echo " tests in: $dir"
        nl
    else
        nl
        ../clr magenta 'failed'
        echo " tests in: $dir"
        nl
        exit 1
    fi

    cd ..
    i=$((i + 1))
done
