#!/usr/bin/env dash

# run all tests given as command line argument where each is a file structured:
# ./[test]/run

run_single() {
    dir="$1"

    if [ $SHOW_OUTPUT = yes ]
    then
        run
    else
        run > /dev/null 2>&1
    fi

    return $?
}

i=1
for raw in "$@"
do
    printf 'test [ %s of %d ]\n' $(./clr bright_yellow $i) $TOTAL_TESTS

    dir="$(dirname "$raw")"
    cd "$dir"
    if run_single "$dir"
    then
        echo ''
        clr cyan 'passed'
        echo " tests in: $dir"
        echo ''
    else
        echo ''
        clr magenta 'failed'
        echo " tests in: $dir"
        echo ''
        exit 1
    fi
    cd ..

    i=$((i + 1))
done
