#!/usr/bin/env dash

# verify a name matches a given set of terms

terms="$1"
dir="$2"

[ -z "$terms" ] && exit 0

old_ifs="$IFS"
IFS=','
for term in $terms
do
    printf '%s' "$dir" | grep -F -q "$term" && exit 0
done
IFS="$old_ifs"

exit 1
