#!/bin/dash

input=$(mktemp)
out=$(mktemp)
err=$(mktemp)
trap 'rm -f $input $out $err' EXIT

touch already.mp4

cd src

cat << EOF > $input
r already
q
EOF

python3 viewer.py < $input > $out 2>$err

cat $out

if ! grep -E -q 'the file .*already\.mp4.* exists in the folder \[.*\]' $err
then
    echo "existence error message was not printed to stderr"
    exit 1
fi

../../clr green 'passed'
echo " test $(basename "$0")"