#!/usr/bin/env dash

input=$(mktemp)
out=$(mktemp)
err=$(mktemp)
trap 'rm -f $input $out $err' EXIT

touch $RENAMES/already.mp4

cat << EOF > $input
r already
q
EOF

python3 -m mve log viewer $CONFIG < $input > $out 2>$err

clr-remover "$err"

if ! grep -F -q "the file 'already.mp4' exists in the folder ['$RENAMES']" $err
then
    echo "existence error message was not printed to stderr"
    exit 1
fi

clr green 'passed'
echo " test $(basename "$0")"
