#!/bin/dash

# set to a non-empty string value to turn on
VIEW=''

../setup-env

[ -n "$VIEW" ] && sed -E -i '' '/^TESTING/s%True%False%' src/config.py
sed -E -i '' '/^USE_MOVIEPY/s%True%False%' src/config.py

test-commands
