#!/bin/dash

cd src

cmds=$(mktemp)
trap 'rm -f $cmds' EXIT

cat << EOF > $cmds
e -1 end command
s 0-58 start command
m 1 2 middle command
w whole command
q
EOF

python3 viewer.py < $cmds
python3 treater.py
