#!/usr/bin/env dash

# see if sed can be used to remove colours

main () {
    full
    bracket_semicolon
    working
}

out="$(mktemp)"
trap 'rm -f "$out"' EXIT

working () {
    echo working
    echo '\033[1;34mfish\033[1;0ming in the river' > "$out"
    sed -E -i '' -e 's///g' "$out"
    grep -F -q '[1;34mfish[1;0ming in the river' "$out"
    echo ''
}

bracket_semicolon () {
    echo bracket_semicolon
    echo '\033[1;34mfish\033[1;0ming in the river' > "$out"
    sed -E -i '' -e 's///g' -e 's/\[.;//g' "$out"
    grep -F '34mfish0ming in the river' "$out"
    echo ''
}

full () {
    echo full
    echo '\033[1;34mfish\033[1;0ming in the river' > "$out"
    sed -E -i '' -e 's///g' -e 's/\[.;(0|3[0-7])m//g' "$out"
    grep -F 'fishing in the river' "$out"
    echo ''
}

main
