#!/usr/bin/env dash

main () {
    full
}

working () {
    echo '\033[1;34mfish\033[1;0ming in the river' > clr
    sed -E -i '' -e 's///g' clr
    grep -F -q '[1;34mfish[1;0ming in the river' clr
}

bracket_semicolon () {
    echo '\033[1;34mfish\033[1;0ming in the river' > clr
    sed -E -i '' -e 's///g' -e 's/\[.;//g' clr
    grep -F '34mfish0ming in the river' clr
}

full () {
    echo '\033[1;34mfish\033[1;0ming in the river' > clr
    sed -E -i '' -e 's///g' -e 's/\[.;(0|3[0-7])m//g' clr
    grep -F 'fishing in the river' clr
}

main
