#!/bin/dash

../setup-env

number() {
    grep -E -o '[0-9]+'
}

if [ $(ls -1 queue | wc -l | number) -ne 0 ]
then
    echo 'the queue was not empty after initial setup'
    exit 1
fi

cd src
exp=$(sed -E -n '/EMPTY_QUEUE/p' constants/error.py | number)

python3 treater.py > /dev/null
status=$?

if [ $exp -ne $status ]
then
    ../../clr 'red' 'failed'
    echo ": $treater.py did not exit with an exit status of $exp (EMPTY_QUEUE)"
    exit 1
fi

../../clr cyan passed
echo " test empty-queue"
