#!/bin/dash

. ../setup-env

number() {
    grep -E -o '[0-9]+'
}

# this test is not meant to be run from src/
# so the configs are not in the previous folder
if [ "$(ls -1  $(basename $MVE_CONFIGS)/$CONFIG/queue | wc -l | number)" -ne 0 ]
then
    echo 'the queue was not empty after initial setup'
    exit 1
fi

cd src
exp=$(sed -E -n '/EMPTY_QUEUE/p' constants/error.py | number)

python3 treater.py $CONFIG > /dev/null
status=$?

if [ $exp -ne $status ]
then
    ../../clr 'red' 'failed'
    echo ": $treater.py did not exit with an exit status of $exp (EMPTY_QUEUE)"
    exit 1
fi

../../clr cyan passed
echo " test empty-queue"
