#!/bin/dash

. ../setup-env

run_test() {
    python3 -m mve no-log focus ../videos/02.mp4 --destination outputs << EOF
5 10
q
EOF
    return $?
}

if ! run_test
then
    echo 'focus did not successfully exit'
    exit 10
fi

# this is wrong on purpose, change to 5 10
if [ ! -e 'outputs/5 10.mp4' ]
then
    echo 'did not edit clip "5 10"'
    exit 20
fi

true
