#!/usr/bin/env dash

# run make using command line flags

. setup-env

export CONFIG=fishing

python3 -m mve log make $CONFIG \
    --source ../videos \
    --renames .. \
    --edits outputs

# folders
[ -d $MVE_CONFIGS/$CONFIG/history ] || exit 10
[ -e $MVE_CONFIGS/$CONFIG/history/.gitkeep ] || exit 15

[ -d $MVE_CONFIGS/$CONFIG/errors ] || exit 20
[ -e $MVE_CONFIGS/$CONFIG/errors/.gitkeep ] || exit 25

[ -d $MVE_CONFIGS/$CONFIG/queue ] || exit 30
[ -e $MVE_CONFIGS/$CONFIG/queue/.gitkeep ] || exit 35

# files

[ -e $MVE_CONFIGS/$CONFIG/config.json ] || exit 40
[ -e $MVE_CONFIGS/$CONFIG/remaining.json ] || exit 50

# source folders
# we check these with Python to avoid json parsing issues
pytest

