#!/bin/dash

cd ..
root_level="$(pwd)"
fail() {
    "$root_level/clr" red failed && printf ': '
}

cd - > /dev/null
../setup-env

rm -r queue
if [ -d queue ]
then
    fail
    echo "queue wasn't properly deleted"
    exit 1
fi
cd src

out=$(mktemp)
err=$(mktemp)
trap 'rm -f $out $err' EXIT

do_test() {
    script=$1
    python3 $script > $out 2>$err
    status=$?
    exp=$(sed -E -n '/NO_QUEUE/p' constants/error.py | grep -E -o [0-9]+)
    if [ $status -ne $exp ]
    then
        fail
        echo "the $script didn't exit with error code $exp (NO_QUEUE)"
        exit 2
    fi

    if [ -s $out ]
    then
        fail
        echo "standard output was produced"
        exit 3
    fi

    if ! grep -E -x -q "queue folder .* does not exist" $err
    then
        fail
        echo "error message wasn't correct"
        cat $err
        exit 4
    fi

    ../../clr blue 'passed'
    echo ": $script"
}

do_test viewer.py
do_test treater.py

echo ''
../../clr cyan 'passed'
echo ': no-queue'
