#!/usr/bin/env dash

. ../setup-env

err="$(mktemp)"
trap 'rm -f "$err"' EXIT

main() {
    load_treatment
    tamper_file
    expect_treater_error
}

load_treatment() {
    if ! python3 -m mve log viewer $CONFIG << EOF
m 5 13 bad
m 3 6 good
q
EOF
    then
        echo 'could not log edits in the viewer'
        return 11
    fi

    true
    return $?
}

tamper_file() {
    # there should only be one enqued file
    seen=no
    for q in $MVE_CONFIGS/$CONFIG/queue/*
    do
        if [ $seen = yes ]
        then
            echo 'more than one file queued'
            return 12
        fi

        # add errors
        sed -E -i '' 's/13/fire/' "$q"

        seen=yes
    done

    true
    return $?
}

expect_treater_error() {
    if python3 -m mve log treater $CONFIG 2>/"$err" >/dev/null
    then
        echo 'treater was run sucessfully after being tampered with'
        return 13
    fi

    clr-remover "$err"
    if ! grep -F -q '[ error ] 1 error occurred during treatment logged in' "$err"
    then
        echo 'incorrect error message printed out for single tampered treater error'
        return 14
    fi

    true
    return $?
}

main
echo 'treater successfully handled one tampered error'
