#!/usr/bin/env dash

fail() {
    clr red failed && printf ': '
}

. setup-env

out=$(mktemp)
err=$(mktemp)
trap 'rm -f $out $err' EXIT

rm -r $RENAMES

# note that these should not work (ie. to the point where prompt is shown)
# in the absence of the renames folder
do_test() {
    script=$1
    python3 -m mve log $script $CONFIG > $out 2>$err
    status=$?
    exp=$(sed -E -n '/NO_RENAMES_FOLDER/p' mve/src/constants/error.py | grep -E -o [0-9]+)
    if [ $status -ne $exp ]
    then
        fail
        echo "the $script didn't exit with error code $exp (NO_RENAMES_FOLDER)"
        echo $status
        exit 2
    fi

    if [ -s $out ]
    then
        fail
        echo "standard output was produced"
        exit 3
    fi

    if ! grep -E -x -q "renames folder .* does not exist" $err
    then
        fail
        echo "error message wasn't correct:"
        sed -E 's/^/    /' $err
        exit 4
    fi

    clr blue 'passed'
    echo ": $script"
}

do_test viewer
# add a throwaway file so the queue isn't empty
touch configs/$CONFIG/queue/blank.json
do_test treater

echo ''
clr cyan 'passed'
echo ': no-renames'
