#!/usr/bin/env dash

. ../setup-env

[ -d benchmark-videos ] && rm -r benchmark-videos
mkdir benchmark-videos

cd benchmark-videos
seq 200 | xargs -I % touch %.mp4
cd ..


echo '[]' > $MVE_CONFIGS/$CONFIG/remaining.json
sed -E -i '' '/SOURCE/s%\[.*\]%["benchmark-videos"]%' $MVE_CONFIGS/$CONFIG/config.json
python3 -m mve log generator $CONFIG
yes d | python3 -m mve log viewer $CONFIG
