#!/bin/dash

../setup-env

[ -d inputs ] && rm -r inputs
mkdir inputs

cd inputs
seq 200 | xargs touch
cd ..

cd src
echo '[]' > remaining.json
sed -E -i '' '/^SOURCE/s%\[.*\]%["..", "inputs"]%' config.py
python3 generator.py
yes d | python3 viewer.py > output.txt
cat output.txt