#!/bin/dash

. ../setup-env

cd src

printf 'e -5 dummy
q' | python3 moment.py \
    --source ../../videos \
    --dest ../outputs \
    --testing \
    || exit 10

[ -e ../outputs/dummy.mp4 ] || exit 20

