#!/bin/dash

[ -d outputs ] && rm -r outputs
mkdir outputs

cp ../../mve/src/config.py .
cp ../../mve/src/constants/video_editing.py .  

cat << EOF > edit.py
import subprocess
import moviepy.editor as mvp
import config as cfg
import video_editing as vde

EOF

sed -E -n '/^def edit_video\(/,/^def handle_error\(/p' ../../mve/src/treater.py | sed -E '$d' >> edit.py

pytest --disable-warnings