#!/usr/bin/env dash

main() {
    # test_start
    test_whole
}

test_start() {
    export CONFIG=other

    python3 -m mve log make $CONFIG \
        --source='../videos' --renames=$RENAMES --edits=$EDITS \
        --testing --use-moviepy \
        || exit 11

    python3 -m mve log generator $CONFIG 
    if ! python3 -m mve log viewer $CONFIG << EOF
s 4 start command
q
EOF
    then
        exit 11
    fi

    python3 -m mve log treater $CONFIG || exit 12

    echo 'successfully tested s command using moviepy'
}

# to save time on edit make a smaller video then run whole on that
test_whole() {
    export CONFIG=edit-video

    export EDITS=edited
    [ -d $EDITS ] && rm -r $EDITS
    mkdir $EDITS

    python3 -m mve log make $CONFIG \
        --source='../videos' --renames=$RENAMES --edits=$EDITS \
        --testing --use-moviepy \
        || exit 21

    python3 -m mve log generator $CONFIG
    if ! python3 -m mve log viewer $CONFIG << EOF
m 4 8 edited
q
EOF
    then
        exit 22
    fi

    export CONFIG=run-whole

    export EDITED_FOLDER=$EDITS
    export EDITS=whole-command
    [ -d $EDITS ] && rm -r $EDITS
    mkdir $EDITS

    python3 -m mve log make $CONFIG \
        --source=$EDITED_FOLDER --renames=$RENAMES --edits=$EDITS \
        --testing --use-moviepy \
        || exit 23
    
    python3 -m mve log generator $CONFIG
    if ! python3 -m mve log viewer $CONFIG << EOF
w whole video
q
EOF
    then
        exit 24
    fi

    python3 -m mve log treater $CONFIG || exit 25
    [ -e "$MVE_CONFIGS/$CONFIG/whole video.mp4" ] || exit 26

    echo 'sucessfully tested whole command using moviepy'
}

# TODO: pytest

main
true
