#!/bin/dash

../setup-env

cat << EOF > configs/$CONFIG/config.json
{
    "SOURCE": ["..", "..", "videos"],
    "RENAMES": [".."],
    "DESTINATION": ["..", "outputs"],

    "TESTING": true,
    "RECENT": false,
    "USE_MOVIEPY": false
}
EOF

# test-edit
. ./other-commands
