#!/usr/bin/env dash

export CONFIG=ffmpeg

python3 -m mve log make $CONFIG \
    --source='../videos' --renames=$RENAMES --edits=$EDITS \
    --testing --use-moviepy

python3 -m mve log generator $CONFIG

session="$(mktemp)"
trap 'rm -f "$session"' EXIT

clr () {
    colour="$1"
    msg="$2"
    perl -MTerm::ANSIColor -e 'print color($ARGV[0]) . $ARGV[1] . color("reset")' "$colour" "$msg"
}

pass () {
    clr 'green' 'passed test'
}

fail () {
    clr 'red' 'failed test'
}

check_in_folder () {
    file_name="$1"
    folder="$2"
    if ! grep -F -q "$file_name" -r "$folder"
    then
        fail
        echo ": $file_name wasn't placed in $folder" >&2
        return 1
    fi

    return 0
}

test_helper () {
    cmd="$1"
    file_name="$2"
    errno="$3"

    cat << EOF > "$session"
$cmd $file_name
q
EOF

    python3 -m mve log viewer $CONFIG < "$session" > /dev/null
    check_in_folder "$file_name" "$MVE_CONFIGS/$CONFIG/queue" || exit "$errno"

    python3 -m mve log treater $CONFIG >/dev/null 2>&1 || exit "$errno"
    check_in_folder "$file_name" $MVE_CONFIGS/$CONFIG/history || exit "$errno"
    if ! [ -e "outputs/$file_name.mp4" ]
    then
        fail 
        echo ": $file_name wasn't edited" >&2
        exit "$errno"
    else
        pass
        echo ": $file_name"
    fi
}

test_end () {
    end="$1"
    file_name="$2"
    errno="$3"
    test_helper "e $end" "$file_name" "$errno"
}

test_end '-2' 'negative number' 1
test_end '48' 'natural number' 2
test_end '00-53' 'timestamp' 3
test_end '0-34' 'timestamp no leading 0'

clr 'cyan' "passed all tests"
echo " $0"
