#!/usr/bin/env dash

# ensure that make correctly constructs the folder structure
# this includes gitkeeps for the other config folders

. ../setup-env

export CONFIG=fishing

printf '../videos
../
outputs' | python3 -m mve log make $CONFIG

[ -d $MVE_CONFIGS/$CONFIG/history ] || exit 10
[ -e $MVE_CONFIGS/$CONFIG/history/.gitkeep ] || exit 15

[ -d $MVE_CONFIGS/$CONFIG/errors ] || exit 20
[ -e $MVE_CONFIGS/$CONFIG/errors/.gitkeep ] || exit 25

[ -d $MVE_CONFIGS/$CONFIG/queue ] || exit 30
[ -e $MVE_CONFIGS/$CONFIG/queue/.gitkeep ] || exit 35
