#!/usr/bin/env dash

export CONFIG=bad-recent

python3 -m mve log make $CONFIG \
    --source ../videos --renames $RENAMES --edits $EDITS \
    --testing --recent \
    || exit 10

err="$(mktemp)"
trap 'rm -f "$err"' EXIT

# change true to a number

sed -I '' '/RECENT/ s/true/42/' $MVE_CONFIGS/$CONFIG/config.json

python3 -m mve log generator $CONFIG 2> "$err"
[ $? -eq $BAD_TYPE ] || exit 20

clr-remover "$err"

grep -F -q 'incorrect type for configuration option' $err || exit 21
grep -F -q "[ error ] option 'recent':" $err || exit 22
grep -F -q '[ error ]   exp : bool' $err || exit 23
grep -F -q '[ error ]   got : int' $err || exit 24

# change number to null

sed -I '' '/RECENT/ s/42/null/' $MVE_CONFIGS/$CONFIG/config.json

python3 -m mve log generator $CONFIG 2> "$err"
[ $? -eq $BAD_TYPE ] || exit 30

clr-remover "$err"

grep -F -q 'incorrect type for configuration option' $err || exit 31
grep -F -q "[ error ] option 'recent':" $err || exit 32
grep -F -q '[ error ]   exp : bool' $err || exit 33
grep -F -q '[ error ]   got : NoneType' $err || exit 34
