#!/usr/bin/env dash

export CONFIG=bad-moviepy-threads

python3 -m mve log make $CONFIG \
    --source ../videos --renames $RENAMES --edits $EDITS \
    --testing --moviepy-threads 9 \
    || exit 10

err="$(mktemp)"
trap 'rm -f "$err"' EXIT

# change number to null

sed -I '' '/MOVIEPY_THREADS/ s/9/true/' $MVE_CONFIGS/$CONFIG/config.json

python3 -m mve log generator $CONFIG 2> "$err"
[ $? -eq $BAD_TYPE ] || exit 20

clr-remover "$err"

cat $err

grep -F -q 'incorrect type for configuration option' $err || exit 21
grep -F -q "[ error ] option 'moviepy_threads':" $err || exit 22
grep -F -q '[ error ]   exp : int' $err || exit 23
grep -F -q '[ error ]   got : bool' $err || exit 24
