#!/usr/bin/env dash

. ../setup-env

export BAD_TYPE=$(grep -F BAD_TYPE mve/src/constants/error.py | grep -E -o '[0-9]+')

run_test() {
    num=$1
    type=$2
    option=$3
    script=$4
    name=$5

    printf "test [ %s/7 ] testing bad %s for %s:\n" "$(clr bright_blue $num)" $type "$(clr bright_magenta $option)"
    ./$script > /dev/null || exit "1${num}"
    printf "    bad %s - %s\n" $name "$(clr bright_green passed)"
}

run_test 1 boolean RECENT bad-recent recent
run_test 2 int NUM_PROCESSES bad-num-processes num_processes
run_test 3 boolean USE_MOVIEPY bad-use-moviepy use_moviepy
run_test 4 int MOVIEPY_THREADS bad-moviepy-threads moviepy_threads
run_test 5 boolean TESTING bad-testing testing
run_test 6 boolean BOLD bad-bold bold
run_test 7 boolean VERIFY_NAME bad-verify-name verify_name

echo ''
echo 'successfully tested all options'
