#!/bin/dash

../setup-env

cat src/remaining.json

touch outputs/exists.mp4

run_all() {
    file="$1"
    if ! "$1"
    then
        echo "failed $file"
        exit 1
    fi

    echo ''
    echo "passed tests: $file"
}

run_all test-middle
