#!/bin/dash

[ $# -eq 2 ] || exit 142

PASS=$(../clr green passed)
FAIL=$(../clr red failed)

cmds=$(mktemp)
out=$(mktemp)
err=$(mktemp)
exp_out=$(mktemp)
exp_err=$(mktemp)
trap 'rm -f $cmds $out $err $exp_out $exp_err' EXIT

echo '[ 4 ] - 01.mp4 : [ 4 ] - 01.mp4 : [ success ] viewer exited with 4 files remaining' > $exp_out

cd src

name="$1"
error_msg="$2"

python3 viewer.py $CONFIG > $out 2>$err

../../clr-remover $out
if ! diff $out $exp_out > /dev/null
then
    echo 'out:'
    cat $out
    echo 'exp:'
    cat $exp_out
    echo "$FAIL test $name: stdout incorrect"
    exit 1
fi

echo "$error_msg" > $exp_err
../../clr-remover $err
if ! diff $err $exp_err > /dev/null
then
    echo "$FAIL test $name: stderr incorrect"
    exit 1
fi

echo "$PASS test: $name"
