#!/bin/dash

run-test 'too few args' '[ error ] usage: [m]iddle | [ start ] [ end ] [ name ]' << EOF
m 1 2
q
EOF

run-test 'no args' '[ error ] usage: [m]iddle | [ start ] [ end ] [ name ]' << EOF
m
q
EOF

run-test 'negative start time' '[ error ] the start time must be in the format [ natural number | timestamp in form <[hour]-min-sec> ]' << EOF
m -3 1 bad
q
EOF

run-test 'negative end time' '[ error ] the end time must be in the format [ natural number | timestamp in form <[hour]-min-sec> ]' << EOF
m 10 -4 bad
q
EOF

run-test 'seconds timestamp errors; end bigger than start' "[ error ] the end time '5' must be bigger than the start time '10'" << EOF
m 10 5 bad
q
EOF
