#!/bin/dash

cp -r ../../mve/src .
cd src
echo '[]' > remaining.json

sed -E -i '' '2s%\[.*\]%["../", "../", "videos"]%
3s%\[.*\]%["../"]%
4s%\[.*\]%["../", "outputs"]%' config.py

python3 generator.py