#!/bin/dash

../setup-env
make-videos
make-configs

# to get clr
export PATH="$PATH:$(dirname "$(pwd)")"

fail() {
    clr red failed
    echo " : $1"
    exit $2
}

out=$(mktemp)
err=$(mktemp)
trap 'rm $out $err' EXIT

cd src
python3 generator.py > $out 2>$err || fail 'first generator failed' 10
set -x
test "$(grep -E -o 0. remaining.json | tr '\n' ' ')" = '01 02' || fail "didn't generate right remaining first time" 20

