#!/bin/dash

exp=$(get-err NO_CURRENT_CONFIG)
cd src

good='configs/current.json'
bad='configs/_current.json'
mv "$good" "$bad"

out=$(mktemp)
err=$(mktemp)

clean() {
    mv "$bad" "$good"
    rm $out $err
}
trap clean EXIT

python3 swapper.py tf2 >$out 2>$err
[ $? -eq $exp ] || exit 10

grep -E "the current config file '.*' does not exist" -q $err || exit 20
[ -s $out ] && exit 30

exit 0
