#!/bin/dash

conf=$(get-err NO_CONFIG_CONF_FILE)
rem=$(get-err NO_CONFIG_REMAINING)
cd src

out=$(mktemp)
err=$(mktemp)

clean() {
    rm $out $err
    [ -f _config.py ] && mv _config.py config.py
    [ -f _remaining.json ] && mv _remaining.json remaining.json
}
trap clean EXIT

mv config.py _config.py
python3 swapper.py tf2 >$out 2>$err
[ $? -eq $conf ] || exit 10
grep -E "the config file '.*config\.py.*' does not exist" -q $err || exit 20
[ -s $out ] && exit 30

mv _config.py config.py
mv remaining.json _remaining.json
python3 swapper.py tf2 >$out 2>$err
[ $? -eq $rem ] || exit 10
grep -E "the remaining file '.*remaining\.json.*' does not exist" -q $err || exit 20
[ -s $out ] && exit 30

exit 0
