#!/bin/dash

exp=$(get-err NO_CONFIGS_FOLDER)
cd src
[ -d _configs ] && rm -rf _configs
mv configs _configs

out=$(mktemp)
err=$(mktemp)

clean() {
    rm $out $err
    mv _configs configs
}
trap clean EXIT

python3 swapper.py mc >$out 2>$err
[ $? -eq $exp ] || exit 10

grep -E "the configs folder '.*' does not exist" -q $err || exit 20
[ -s $out ] || exit 30

exit 0
