#!/bin/dash

exp=$(get-err NO_CONFIG)
cd src

out=$(mktemp)
err=$(mktemp)
trap 'rm $out $err' EXIT

python3 swapper.py fishing >$out 2>$err
[ $? -eq $exp ] || exit 10

grep -E "the 'fishing' config folder '.*' does not exist" -q $err || exit 20
[ -s $out ] && exit 30

exit 0
