#!/bin/dash

../setup-env

fail() {
    test_name="$1"
    if [ $? -ne 0 ]
    then
        ../clr red failed
        echo >&2 ": $test_name"
        exit 1
    fi
}

test-args || fail args
no-configs-folder || fail 'no configs folder'
no-such-config || fail "given config doesn't exist"
no-current-file || fail 'no current.json in configs'
no-config-pair || fail 'no config pair src'

exit 0
