#!/bin/dash

exp=$(get-err BAD_COMMAND_LINE_ARGS)
cd src
out=$(mktemp)
err=$(mktemp)
trap 'rm -f $out $err' EXIT

# 0 ARG

python3 swapper.py > $out 2>$err
[ $? -eq $exp ] || exit 1
grep -q -F 'usage: python3 swapper.py [config name]' $err || exit 2
[ -s $out ] && exit 3

# 2 ARG

# want to test multiple args but can't really make the args a param
# + because of string splitting in shell
# so copy and paste tests

echo -n '' > $err

python3 swapper.py mc fishing > $out 2>$err
[ $? -eq $exp ] || exit 1
grep -q -F 'usage: python3 swapper.py [config name]' $err || exit 2
[ -s $out ] && exit 3

exit 0
